abort: fix gcc complaint with applying 'noreturn' attribute
This change fixes this gcc warning:

error: 'abort' specifies less restrictive attribute than its target 'grub_abort':
'noreturn' [-Werror=missing-attributes]

It applies 'noreturn' attribute to abort() declaration as well, which has
already been declared as an alias to grub_abort().

Signed-off-by: Ani Sinha <ani@anisinha.ca>